services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "9000"

  web:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    ports:
      - "80"
