services:
  laravel-app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    expose:
      - 9000

  nginx-server:
    image: nginx
    depends_on:
      - laravel-app
    volumes:
      - ./:/var/www/html
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
    environment:
      - API_URL=$SERVICE_FQDN_API
